---
title: "sta130proj"
output:
  pdf_document: default
  html_document: default
date: "2023-03-18"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## R Markdown


```{r cars}

library(tidyverse)
```

```{r}
# load basic data
library(rhdf5)
header <- h5ls("STA130_APOGEE.h5")
header
```

```{r}
glimpse(header)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


```{r}
# test a simple visualization from two tibble we are focusing on
effective_temp <- "STA130_APOGEE.h5" %>% h5read("teff") %>% as_tibble()
logg_gravity <- "STA130_APOGEE.h5" %>% h5read("logg") %>% as_tibble()
ggplot() + aes(x=effective_temp$value, y=logg_gravity$value) + geom_bin_2d(bins=200)
```

```{r}
# this is the linear regression analyze of our second research problem
et = "STA130_APOGEE.h5" %>% h5read("teff")
loggra = "STA130_APOGEE.h5" %>% h5read("logg")
df <- data.frame(loggra, et)
model <- lm(et ~ loggra, data = df) %>% summary
ggplot(df, aes(x = loggra, y = et)) +
  geom_point() +
  geom_smooth(method = "lm")

model
```

```{r}
# this is multilinear regression analyze of question 3
feh <- "STA130_APOGEE.h5" %>% h5read("fe_h") %>% as_tibble() 
feh_abundance <- feh %>% mutate(abundance = case_when(value < 0 ~ 0, value >= 0 ~ 1))

cah <- "STA130_APOGEE.h5" %>% h5read("ca_h") %>% as_tibble() 
cah_abundance <- cah %>% mutate(abundance = case_when(value < 0 ~ 0, value >= 0 ~ 1))

alh <- "STA130_APOGEE.h5" %>% h5read("al_h") %>% as_tibble() 
alh_abundance <- alh %>% mutate(abundance = case_when(value < 0 ~ 0, value >= 0 ~ 1))

mgh <- "STA130_APOGEE.h5" %>% h5read("mg_h") %>% as_tibble() 
mgh_abundance <- mgh %>% mutate(abundance = case_when(value < 0 ~ 0, value >= 0 ~ 1))

df2 <- data.frame(loggra, cah = cah_abundance, alh = alh_abundance, mgh = mgh_abundance, feh = feh_abundance)
df2

model3 <- lm(loggra ~ cah.abundance + alh.abundance +mgh.abundance +  feh.abundance, data = df2) %>% summary
model3


df3 <- data.frame(loggra, ca_al_abundance_interact = cah$value + alh$value, cah = cah$value, alh = alh$value, mgh = mgh$value, feh = feh$value)

df3 %>% ggplot(aes(x = loggra, y = ca_al_abundance_interact)) +
  geom_point() +
  geom_smooth(method = "lm")


```

```{r}
#this is the new linear regression analyze and visualization of heavy elements respectively
df4 = data.frame(loggra, cah = cah$value, alh = alh$value, mgh = mgh$value, feh = feh$value)

lm(loggra ~ mgh, data = df4) %>% summary
lm(loggra ~ feh, data = df4) %>% summary
lm(loggra ~ alh, data = df4) %>% summary
lm(loggra ~ cah, data = df4) %>% summary
df4 %>% ggplot(aes(x = loggra, y = mgh)) +
  geom_point() +
  geom_smooth(method = "lm")

df4 %>% ggplot(aes(x = loggra, y = feh)) +
  geom_point() +
  geom_smooth(method = "lm")

df4 %>% ggplot(aes(x = loggra, y = alh)) +
  geom_point() +
  geom_smooth(method = "lm")

df4 %>% ggplot(aes(x = loggra, y = cah)) +
  geom_point() +
  geom_smooth(method = "lm")

```
```{r}
df4 %>% summarise(correlationfeh = 
                              cor(loggra, feh))
df4 %>% summarise(correlationcah = 
                              cor(loggra, cah))
df4 %>% summarise(correlationmgh = 
                              cor(loggra, mgh))
df4 %>% summarise(correlationalh = 
                              cor(loggra, alh))
```
```{r}
summary(lm(feh ~ loggra, data = df4))
summary(lm(cah ~ loggra, data = df4))
summary(lm(mgh ~ loggra, data = df4))
summary(lm(alh ~ loggra, data = df4))
```

